# Generated by Django 4.0.2 on 2023-02-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRwebApp', '0004_alter_paginas_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginas',
            name='field_name',
            field=models.ImageField(blank=True, null=True, upload_to='terminos'),
        ),
    ]
