# Generated by Django 4.0.2 on 2023-02-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRwebApp', '0008_blog_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=250, verbose_name='Título')),
                ('respuesta', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'FAQS',
                'verbose_name_plural': 'FAQS',
            },
        ),
        migrations.AlterField(
            model_name='paginas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='JRwebApp/terminos'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='JRwebApp/planes'),
        ),
    ]
