# Generated by Django 4.0.2 on 2023-02-13 01:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRwebApp', '0009_faqs_alter_paginas_imagen_alter_planes_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=250, verbose_name='Etiqueta')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Etiquetas Blog',
                'verbose_name_plural': 'Etiquetas Blog',
            },
        ),
        migrations.AlterField(
            model_name='faqs',
            name='pregunta',
            field=models.CharField(max_length=250, verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='respuesta',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Respuesta'),
        ),
    ]
