# Generated by Django 4.0.2 on 2023-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestarwebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas',
            name='contenido',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
