# Generated by Django 4.0.2 on 2023-02-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestarwebApp', '0003_alter_paginas_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
