# Generated by Django 4.0.2 on 2023-02-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienestarwebApp', '0005_paginas_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paginas',
            old_name='field_name',
            new_name='imagen',
        ),
    ]
