# Generated by Django 4.0.2 on 2023-02-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestarwebApp', '0006_rename_field_name_paginas_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='terminos')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Planes',
                'verbose_name_plural': 'Planes',
            },
        ),
    ]
