# Generated by Django 4.0.2 on 2023-02-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienestarwebApp', '0010_etiquetas_alter_faqs_pregunta_alter_faqs_respuesta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etiquetas',
        ),
    ]
