# Generated by Django 4.0.2 on 2023-10-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestarwebApp', '0017_paginas_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginas',
            name='pdf',
            field=models.FileField(null=True, upload_to='pags/bienestarwebApp/pdfs'),
        ),
    ]
