# Generated by Django 4.0.2 on 2023-12-20 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('calle', models.CharField(max_length=50)),
                ('no_ext', models.IntegerField()),
                ('no_int', models.IntegerField()),
                ('colonia', models.CharField(max_length=50)),
                ('codigo_postal', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('referencias', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
