# Generated by Django 4.0.2 on 2023-12-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_nombre_venta_nombre_remove_venta_id_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
