# Generated by Django 4.0.2 on 2023-12-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='no_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
