# Generated by Django 4.0.2 on 2023-12-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_cantidad_venta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='apellido',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
