# Generated by Django 4.0.2 on 2023-12-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='no_ext',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='no_int',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
