# Generated by Django 4.0.2 on 2023-12-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_venta_codigo_postal_alter_venta_no_ext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
