# Generated by Django 4.0.2 on 2024-01-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_venta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='aceptar_aviso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='aceptar_terminos',
            field=models.BooleanField(default=False),
        ),
    ]
