# Generated by Django 4.0.2 on 2024-07-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_venta_aceptar_aviso_venta_aceptar_terminos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('mp_link', models.CharField(blank=True, max_length=900, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Oferta chip',
                'verbose_name_plural': 'Ofertas Chip',
            },
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.IntegerField(choices=[(100, 'Obten tu Chip'), (50, 'Paquete 50'), (60, 'Paquete 60'), (99, 'Paquete 99'), (100, 'Paquete 100'), (120, 'Paquete 120'), (200, 'Paquete 200'), (230, 'Paquete 230')]),
        ),
    ]
