# Generated by Django 4.0.2 on 2024-07-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_chipoffers_alter_venta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipoffers',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
