# Generated by Django 4.0.2 on 2024-07-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_venta_aceptar_aviso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='paquete',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.IntegerField(blank=True, choices=[(100, 'Obten tu Chip'), (50, 'Paquete 50'), (60, 'Paquete 60'), (99, 'Paquete 99'), (100, 'Paquete 100'), (120, 'Paquete 120'), (200, 'Paquete 200'), (230, 'Paquete 230')], null=True),
        ),
    ]
