# Generated by Django 4.0.2 on 2024-07-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_venta_paquete_alter_venta_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='paquete',
        ),
        migrations.AlterField(
            model_name='venta',
            name='apellido',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='calle',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='celular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigo_postal',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='colonia',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='municipio',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='no_ext',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
