# Generated by Django 4.0.2 on 2024-07-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_venta_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
